### ISSUE TITLE
[Easy onboarding] Add the elements of easy onboarding

### ISSUE THREAD

**Issue by kovaletskaterina** [SOURC3XYZ/sourc3#106]
1. When the opportunity to complete verification later will be added, add the "Confirm later" button on the Secret phrase screen to see your secret phrase later on the settings screen.
![image](https://user-images.githubusercontent.com/83376495/173411064-d7376ad8-fa26-4b55-8636-45a594567176.png)
2. On the secret phrase confirmation screen add the "You can skip the confirmation." phrase.
![image](https://user-images.githubusercontent.com/83376495/173411475-7002ef75-d0d1-47ff-8808-6402eebbf9ed.png)

**Comment by VikMaevskaya** [comment]
irrelevant
