### ISSUE TITLE
Branch is not pushed if there is no data

### ISSUE THREAD

**Issue by anatolse** [SOURC3XYZ/sourc3#124]
if there are no commits to push and you simply upload new ref, there is no transaction
Expected: new re should be stored to block chain

**Comment by KatsiarynaV** [comment]
There is still no transaction if there are no commits on the new branch

![08](https://user-images.githubusercontent.com/68267190/179538710-a8f996f7-0925-4c76-8a60-050a7560ddf9.jpg)

**Comment by KatsiarynaV** [comment]
Checked
