### ISSUE TITLE
Invalid commit time

### ISSUE THREAD

**Issue by anatolse** [SOURC3XYZ/sourc3#128]

**Comment by SixStringer91** [comment]
![Image](https://user-images.githubusercontent.com/73410591/176305968-43acc1df-c1b6-4deb-82e0-c95b12524e76.png)



![Image](https://user-images.githubusercontent.com/73410591/176306029-8ceb8919-7998-43b9-90ef-95089cd5a614.png)

**Comment by KatsiarynaV** [comment]
Time is incorrect. Repo was just updated but time is displaying 3 hours ago

![06](https://user-images.githubusercontent.com/68267190/176895143-4c4cf236-6d3c-4086-b9da-0a5ddc80141a.jpg)

**Comment by SixStringer91** [comment]
done. time of the commit is bound to the moment of its creation locally

**Comment by KatsiarynaV** [comment]
Checked
