### ISSUE TITLE
Keyboard support (tab and enter keys)

### ISSUE THREAD

**Issue by KatsiarynaV** [SOURC3XYZ/sourc3#129]
1. Password input field should process 'Enter' key 
![01](https://user-images.githubusercontent.com/68267190/175056685-9a8749e6-c893-4b0c-b7cc-85f84482c36b.jpg)
![02](https://user-images.githubusercontent.com/68267190/175056691-057354ba-3156-4d8d-b01e-9cd7bac696fd.jpg)

2. If possible when user uses 'tab' key make selected button highlighted
![03](https://user-images.githubusercontent.com/68267190/175057009-d010c8dc-a786-4778-9f0c-e77460ec668e.jpg)

**Comment by JenkJS** [comment]
- [ ] Password input field should process 'Enter' key  Login page

- [ ] Password input field should process 'Enter' key  Password page

- [ ] If possible when user uses 'tab' key make selected button highlighted

- [ ] Option paste full seed phrase for restore
