### ISSUE TITLE
identity change

### ISSUE THREAD

**Issue by SixStringer91** [SOURC3XYZ/sourc3#134]
- [x] make it possible to change identity on the web

- [ ] make it possible to change identity on the desktop

**Comment by SixStringer91** [comment]
**web**

![Image](https://user-images.githubusercontent.com/73410591/176305014-e7e85c0f-65be-4e81-9a42-c8f9df6bff9e.png)

**Comment by SixStringer91** [comment]
Identity management on the desktop client is no longer needed, so I move the task to done

**Comment by KatsiarynaV** [comment]
When connecting to the web client, organizations, projects and repos of the first identity are always displayed, even if you connect to another one

https://user-images.githubusercontent.com/68267190/177998281-869bae35-58b9-4968-94bd-44f52c756cf3.mp4

**Comment by beam-mw** [comment]
Won't be implemented in Alpha
