### ISSUE TITLE
Open instruction page when 'Connect' clicked and extension not installed

### ISSUE THREAD

**Issue by beam-mw** [SOURC3XYZ/sourc3#143]
Currently when 'Connect' is clicked and extension is not installed Github page is opened. 

Instead, we need to show a detailed instructions page on how to install developer version of the Web Client (from sourc3, NOT Github)
This means that the build of Web Client should be (for now) uploaded to a new repo 'Sourc3 Releases'

**Comment by VikMaevskaya** [comment]
Download extension page desing https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=2701%3A419

**Comment by kovaletskaterina** [comment]
Checked
