### ISSUE TITLE
While cloning a repo via 'git clone' command, the error 'IPFS call failed' appears

### ISSUE THREAD

**Issue by kovaletskaterina** [SOURC3XYZ/sourc3#147]
When you clone a repo by a 'git clone' command, the repo doesn't cloned and 'Error: IPFS call failed' message appears.
**Steps to reproduce:**
1. Open the desktop client.
2. Press the 'Sign in' button.
3. Enter your password and press the 'Sign in' button.
4. Press the three dots menu on the 'All repositories' screen.
5. Tap the 'Clone' button.
6. Open the Git Bash and cd to appropriate folder.
7. Type in the 'git clone' command and passed the copied repository path.
8. Press enter.
**Expected result:** the repo is cloned.
![Image](https://user-images.githubusercontent.com/83376495/177138329-143a4d28-4701-4cda-b63e-967e23559f30.png)
**Actual result:** Error: IPFS call failed.
![Image](https://user-images.githubusercontent.com/83376495/177138398-93277483-2ef8-4c01-9a00-fba98158b666.png)

**Comment by KatsiarynaV** [comment]
Checked
