### ISSUE TITLE
Log in screen to add restore link

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#165]
on the Log in screen we need to add "restore with a secret phrase" 

https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=1373%3A382

<img width="1033" alt="Снимок экрана 2022-07-12 в 10 32 25" src="https://user-images.githubusercontent.com/94360080/178434647-c3b09e35-34e2-407f-9e29-fd20b4b3ab8e.png">

**Comment by alexandrashelenkova** [comment]
Resyore flow is here https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=1373%3A382
Please also rename this button into sign in or restore
<img width="821" alt="Screenshot 2022-07-12 at 19 32 54" src="https://user-images.githubusercontent.com/7249484/178480626-60780c77-4cf3-491c-b2d6-9816474cecc3.png">

**Comment by VikMaevskaya** [comment]
<img width="718" alt="Снимок экрана 2022-07-14 в 11 16 35" src="https://user-images.githubusercontent.com/94360080/178941635-8c1ecb4c-2fa4-459c-8773-12d9e8b562f0.png">

**Comment by kovaletskaterina** [comment]
Now it is implemented in such a way:
![image](https://user-images.githubusercontent.com/83376495/180192514-1dcf4177-4111-4a65-817b-cee9ce5663fc.png)
