### ISSUE TITLE
Add mobile wallet protocol support

### ISSUE THREAD

**Issue by anatolse** [SOURC3XYZ/sourc3#177]
Flow for the mobile node.
Create/Restore wallet.
1. download https://mobile-restore.beam.mw/dappnet/dappnet_recovery.bin and store int locally, show progress
2. `./beam-wallet-dappnet init/restore --seed_phrase=<>`
3. `./beam-wallet-dappnet import_recovery --file_location=<>`, show progress
4. add the option `--request_bodies=true` to `./wallet-api-dappnet`

On the next launches simply pass `--request_bodies=true` to `./wallet-api-dappnet`

**Comment by SixStringer91** [comment]
was implemented, but decided to use fast sync on the node instead
