### ISSUE TITLE
Disable input of cyrillic characters

### ISSUE THREAD

**Issue by KatsiarynaV** [SOURC3XYZ/sourc3#179]
Disable input of cyrillic characters for all fields

![01](https://user-images.githubusercontent.com/68267190/183426979-55c982c7-8601-4467-82ed-8f093cda2ef0.jpg)
![02](https://user-images.githubusercontent.com/68267190/183426985-5e3e6fcb-ffe3-4e87-a08b-2110244d8806.jpg)

**Comment by kovaletskaterina** [comment]
Checked.
You still can enter Cyrillic symbols, but the "Continue" button is disabled, so the organization/project/repo isn't saved.
