### ISSUE TITLE
Add "connect GitHub" button

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#181]
We need to add "connect GitHub" button:
1. web site https://www.sourc3.xyz/
2. web app, main page https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=1714%3A856
3. web app top menu https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=1630%3A750

for par 1, 2 add info clickable link "More details"
for 3 add info icon or info link

**Comment by alexandrashelenkova** [comment]
1. Added the button (More details will add after there gonna be a page ready (waiting for the text))
<img width="1920" alt="Screenshot 2022-08-10 at 11 20 50" src="https://user-images.githubusercontent.com/7249484/183806738-272a75a4-1f2b-482b-a8f1-ea5bf4eaaa94.png">

2. Added the button here 
<img width="1440" alt="fisrt" src="https://user-images.githubusercontent.com/7249484/183806828-bf127ce6-bf2d-491f-9431-b3c5486cd28d.png">

3. Added button in the menu (also had to move user balance under his username)
<img width="1057" alt="Screenshot 2022-08-10 at 11 30 01" src="https://user-images.githubusercontent.com/7249484/183806993-666190ee-d6c0-4f41-8cc9-180500c3907b.png">

@VikMaevskaya in the web app should the button change after connection? Into Disconnect Github? Or Github username? How's that gonna work?

**Comment by VikMaevskaya** [comment]
@alexandrashelenkova after connection the button will be disappeared
