### ISSUE TITLE
Info page for More details "connect GitHub"

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#182]
Separate page with SOURC3 visual elements

1. Text area (Later from Tom)
2. Button "Connect GitHub"

**Comment by alexandrashelenkova** [comment]
The page draft is here https://www.sourc3.xyz/why-connect-to-github
Waiting for the text, so I can add it and add link to that page on the Home page.

**Comment by alexandrashelenkova** [comment]
Page design is updated (also the main page on the website).
