### ISSUE TITLE
Create repo changes

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#186]
we need some changes in design:

https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=1947%3A1258

Repo creation should look like this + add public (auto choice) or private
<img width="607" alt="Снимок экрана 2022-08-11 в 15 35 35" src="https://user-images.githubusercontent.com/94360080/184135564-b6f4350e-628a-410b-bdb6-ad038e772419.png">

**Comment by alexandrashelenkova** [comment]
The screen is updated in figma (same link)


![Image](https://user-images.githubusercontent.com/7249484/184868309-91fece7c-f48f-4fa2-93fc-0570912401c5.png)
