### ISSUE TITLE
Add additional fields to organizations, projects, users

### ISSUE THREAD

**Issue by iKapitonau** [SOURC3XYZ/sourc3#192]
Add the following fields to organizations:
- short description
- about
- website
- twitter
- linkedin
- instagram
- telegram
- discord
- members
- tags
- tech stack
- logo

Add the following fields to projects:
- logo
- description
- website
- twitter
- linkedin
- instagram
- telegram
- discord
- members
- tags

Add the following fields to users:
- avatar
- website
- twitter
- linkedin
- instagram
- telegram
- discord
- organizations list
- projects list
- description
- rating

**Comment by KatsiarynaV** [comment]
Checked
