### ISSUE TITLE
Create a user page

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#195]
A user has an access to the profile settings in the menu
<img width="531" alt="Снимок экрана 2022-08-16 в 14 05 04" src="https://user-images.githubusercontent.com/94360080/184864659-df723fb4-9ac5-4707-abc1-97a387c1ec00.png">

1. User Pic
2. Name, nickname, mail (option visible or not), user id 
3. User's Organisations
4. User's Projects
5. Short description
6. Social net + website
7. Tabs -> Project, Repos, Organisations

**Comment by alexandrashelenkova** [comment]
Profiles screen are here https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=3362%3A434

My profile + editing
<img width="1440" alt="my profile" src="https://user-images.githubusercontent.com/7249484/184888378-52f0786a-d63a-4bdf-99a5-08fc3f719f85.png">
<img width="1440" alt="Edit profile" src="https://user-images.githubusercontent.com/7249484/184888395-fdd987a7-5f2b-4837-b0a3-ceade3b3da23.png">

Other user's profile
<img width="1440" alt="my profile" src="https://user-images.githubusercontent.com/7249484/184888414-cd0040c0-dc5d-4a73-9a42-18928015e8c3.png">
