### ISSUE TITLE
Change SOURC3 logo  SOURC3 Alpha

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#196]
Change logo for all pages

https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=3295%3A672
<img width="500" alt="Снимок экрана 2022-08-22 в 14 27 52" src="https://user-images.githubusercontent.com/94360080/185910615-29884cab-6dc1-4a06-a9c6-203d617e5e47.png">

**Comment by kovaletskaterina** [comment]
Checked
