### ISSUE TITLE
add the ability to upload a picture to ipfs

### ISSUE THREAD

**Issue by SixStringer91** [SOURC3XYZ/sourc3#201]
Add the ability to upload a picture to ipfs from web page

**Comment by SixStringer91** [comment]
implemented the endpoint on cache service (/upload)
now need to implement custom hook on web page

**Comment by SixStringer91** [comment]
implemented hook for uploading imgs to ipfs. can check on /upload routing (on web app)

**Comment by kovaletskaterina** [comment]
There is a mistake, while uploading a picture
![image](https://user-images.githubusercontent.com/83376495/187212945-7d1d5cf2-7897-44e2-8efe-26600f2a655d.png)

**Comment by SixStringer91** [comment]
fixed. max size of downloading file is 750kb

**Comment by kovaletskaterina** [comment]
Checked
![image](https://user-images.githubusercontent.com/83376495/187720222-d01356ab-4146-4716-b25c-4f3379fc4177.png)
