### ISSUE TITLE
temporary delete the elements from the main page

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#219]
Stop showing - red squares
change text - second colour square

Text:
SOURC3 is a Web3-native, decentralized platform for on-chain reputation management.

Connect your GitHub to bring your contributions on-chain.

<img width="1680" alt="Снимок экрана 2022-10-05 в 07 15 36" src="https://user-images.githubusercontent.com/94360080/193980289-a99efd11-d27f-4564-afad-5cabab44f0f8.png">

**Comment by KatsiarynaV** [comment]
Checked
