### ISSUE TITLE
Onboarding title position + scroll

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#223]
Titles must have one position, one level.
please, **scroll is must have**

<img width="1680" alt="Снимок экрана 2022-10-07 в 09 45 56" src="https://user-images.githubusercontent.com/94360080/194498450-06a090d9-2e4f-4c5f-afb2-d2cb07da2862.png">

**Comment by VikMaevskaya** [comment]
is it done?

**Comment by KatsiarynaV** [comment]
Checked
