### ISSUE TITLE
app source the Main, add two buttons

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#224]
Two buttons appears after gitconnect
don't move any visual details, we have enough free space
**Continue onboarding** - goes to the first skipped onboarding step
**Back to my profile** - goes to the user profile

https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=5067%3A505

<img width="894" alt="Снимок экрана 2022-10-07 в 10 52 38" src="https://user-images.githubusercontent.com/94360080/194501654-b6fbbaea-a5ed-4a73-b194-6d31cdfd651a.png">

**Comment by kovaletskaterina** [comment]
Checked
