### ISSUE TITLE
Start screen

### ISSUE THREAD

**Issue by gingervik** [SOURC3XYZ/sourc3#48]
On this screen, a user should be able to create a new acc or login into existing
Also may be we need to display app version
How it looks now
![start screen](https://user-images.githubusercontent.com/28015224/164707777-f264df86-503a-4e5d-95fc-629441bca501.jpg)

**Comment by kovaletskaterina** [comment]
1. The font on the start screen should be as on the design.
2. The word "builds" on the "Where Web3 Builds." should start with an uppercase letter. Also, there should be a dot at the end of this phrase.
3. The word "started" on the "Get started" button should start with the lowercase letter.
![image](https://user-images.githubusercontent.com/83376495/173335396-273dda47-881d-406c-b5b5-c70042cb79ec.png)

**Comment by kovaletskaterina** [comment]
According to the design, the "Get started" button should be black with orange frame. The text on the button should also be orange.
![Image](https://user-images.githubusercontent.com/83376495/173795672-22d25ba1-004b-4327-8255-ab7d591f9b38.png)

**Comment by KatsiarynaV** [comment]
Please, make text and letter spacing a little bigger for 'desktop client' text

![01](https://user-images.githubusercontent.com/68267190/174785336-fffceba2-972b-48a3-ae11-66c20571871d.jpg)

**Comment by KatsiarynaV** [comment]
Checked
