### ISSUE TITLE
New user creation flow

### ISSUE THREAD

**Issue by gingervik** [SOURC3XYZ/sourc3#49]
it's really similar to the new wallet creation in Beam

How it looks now
![get started](https://user-images.githubusercontent.com/28015224/165050838-b121c074-79ed-4fb2-873d-e36465fa6b2f.jpg)
![verify seed](https://user-images.githubusercontent.com/28015224/165050830-51be4f1a-3478-4954-9ea3-186e2fd8535e.jpg)
![node sync](https://user-images.githubusercontent.com/28015224/165050835-c17d7d3a-1d83-42f2-8276-1eee49d03164.jpg)
![node sync1](https://user-images.githubusercontent.com/28015224/165050833-af370d10-9d12-4514-a0b2-819b74f93ca9.jpg)
![wallet created-restored](https://user-images.githubusercontent.com/28015224/165050827-49e1e675-0b3b-4b05-9257-ad91906800a7.jpg)

**Comment by kovaletskaterina** [comment]
1. On the seed phrase confirmation screen hide the "You can skip the confirmation." phrase till adding the appropriate opportunity.
According to the design on the seed phrase confirmation screen should be two columns and three rows.
The word "Complete" on the "Confirm phrase" button should be replaced by "Confirm".
![image](https://user-images.githubusercontent.com/83376495/173357869-f3b9db45-dd8f-410a-9e56-4ac5eb43e8fd.png)
2. The password requirements should be executed as on the design.
The "Get started" button should be #FF791F color, it also should be above and visible.
The word "started" on the "Get started" button should start with the lowercase letter.
![image](https://user-images.githubusercontent.com/83376495/173359055-4abff98d-1d37-4647-9c88-9d43ba490603.png)
3. After entering and confirmation a password, under the password field, there should be the message that characterizes password strength.
![image](https://user-images.githubusercontent.com/83376495/173361340-2f3adc55-d3a7-4e9b-84e7-5dad989e3d46.png)
4. Add the "back" button on the "Unpacking blockchain info (XX%)" screen.
![image](https://user-images.githubusercontent.com/83376495/173362799-b009e129-f31f-4dc6-8429-7005b9a22907.png)
5. The "Get started" button should be #FF791F color.
The word "started" on the "Get started" button should start with the lowercase letter and there should be no exclamation mark.
![image](https://user-images.githubusercontent.com/83376495/173363294-5c8669f9-1854-4cdc-b5e2-a3faee30ba71.png)

**Comment by kovaletskaterina** [comment]
Checked
