### ISSUE TITLE
Log in/ Log out to existing user profile flow

### ISSUE THREAD

**Issue by gingervik** [SOURC3XYZ/sourc3#50]
It should allow to log in already existing users
![sign in](https://user-images.githubusercontent.com/28015224/165051063-a4fc487d-e994-494b-9a7d-98d2ca658e99.jpg)

forgot password - as restore in beam wallet. 

For logout - a new screen is needed
![log out](https://user-images.githubusercontent.com/28015224/165051343-0126c7f7-c8b3-42b9-bfe2-90427b39bf47.jpg)

**Comment by kovaletskaterina** [comment]
- Restore flow and Log in screen are checked.
- The logout will be checked after completing https://github.com/SOURC3XYZ/sourc3/issues/131

**Comment by kovaletskaterina** [comment]
Checked
