### ISSUE TITLE
Add menu design

### ISSUE THREAD

**Issue by gingervik** [SOURC3XYZ/sourc3#57]
Through this menu, a user should be able to 
- add a new repository
- clone repository
- add an existing repository
- create a new organisation
    - create new project in the organisation   
    
How it looks now
![clone rep](https://user-images.githubusercontent.com/28015224/165053129-885a7b87-377c-4d58-8de2-af45cca17bc1.jpg)
![add new rep](https://user-images.githubusercontent.com/28015224/165053132-db7a190f-b7f3-405c-a04a-4186da1b565b.jpg)
![add menu](https://user-images.githubusercontent.com/28015224/165053139-ca3d6ac7-e45a-4228-a834-5dcf0a17e1ab.jpg)

**Comment by kovaletskaterina** [comment]
1. The contract doesn't provide for the possibility to create a repository without an organization.
2. Moved to https://github.com/SOURC3XYZ/sourc3/issues/157
3. Moved to https://github.com/SOURC3XYZ/sourc3/issues/158
4. Checked.
5. Checked.
