### ISSUE TITLE
Create new organisation

### ISSUE THREAD

**Issue by gingervik** [SOURC3XYZ/sourc3#68]

**Comment by VikMaevskaya** [comment]
create a new organization flow

![Image](https://user-images.githubusercontent.com/94360080/171628978-e0ff7d0c-83d7-4131-a4b6-acf85a5be93d.png)

**Comment by alexandrashelenkova** [comment]
New designs are here https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=1947%3A1758

**Comment by kovaletskaterina** [comment]
irrelevant
