### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by gingervik** [SOURC3XYZ/sourc3#72]
Now it looks like this when user try to open a wrong page
<img width="1483" alt="Screenshot 2022-05-10 at 15 59 38" src="https://user-images.githubusercontent.com/28015224/167659536-d5364a60-f60a-4f0d-88d3-f462601a9451.png">

**Comment by kovaletskaterina** [comment]
Checked.
At the moment the following design is implemented:
![image](https://user-images.githubusercontent.com/83376495/185091668-18d8f3d4-8a4c-441d-a429-efc7b902b40a.png)
