### ISSUE TITLE
Extension download page

### ISSUE THREAD

**Issue by gingervik** [SOURC3XYZ/sourc3#73]
When user click on "connect" and there is no installed wallet extension we need to redirect him to page with instructions and link to the wallet extension in web store

![Image](https://user-images.githubusercontent.com/28015224/168016574-bd6df758-7438-4866-add1-3c191604870c.png)

**Comment by SixStringer91** [comment]
on /download route

**Comment by kovaletskaterina** [comment]
- Redirection is checked.
- The choosing of wallet you would like to connect moved to https://github.com/SOURC3XYZ/sourc3/issues/188
