### ISSUE TITLE
Main page change

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#74]
https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=1714%3A856

1. "where web3 builds" to " Building <new line> the Web3-way"

2. text  to "Building to benefit the developer community, SOURC3 is a Web3-native, decentralised platform for software development"

3. add to footer:

- copyright Sourc3 (clickable to https://www.sourc3.xyz)
- Twitter icon: https://twitter.com/SOURC3xyz
- Discord icon: https://discord.gg/FpE9VfB6
- ?Mail icon (contact to us) 

In the nearest future we will have more links to docs, help, etc.

**Comment by VikMaevskaya** [comment]
@alexandrashelenkova add copyright please

**Comment by kovaletskaterina** [comment]
1) The text on the "Connect" button should be black #000000 and start with an uppercase letter.
2) After the "Building the Web3 way." should be a dot.
3) There shouldn't be a dash between the words "...Web3 way."
4) After the "Building to benefit the developer community, SOURC3 is a Web3-native, decentralized platform for software development." should be a dot.
5) The "Contact us" button doesn't work as it should.
![image](https://user-images.githubusercontent.com/83376495/178260208-b068fcb6-79e7-4adf-bbc5-4b658b02d476.png)
6) On the Discord button is incorrect link.
![image](https://user-images.githubusercontent.com/83376495/178260074-1ce178bc-1d70-48d4-8e4b-63ee784fa58f.png)

**Comment by kovaletskaterina** [comment]
Checked on https://sourc3-masternet.netlify.app/

**Comment by kovaletskaterina** [comment]
According to the last updates, there shouldn't be a dot after the "Building the Web3 way"

**Comment by kovaletskaterina** [comment]
Checked
