### ISSUE TITLE
User menu change

### ISSUE THREAD

**Issue by VikMaevskaya** [SOURC3XYZ/sourc3#76]
https://www.figma.com/file/3UUMChv0qaOOkHoddpEFgA/SOURC3?node-id=1630%3A750
<img width="410" alt="Снимок экрана 2022-05-17 в 14 36 49" src="https://user-images.githubusercontent.com/94360080/168802104-4701b238-e4b4-45ab-bc77-8b65c355f61b.png">

between Support and Log out add a Separate Section and divid it grey line:

SOURC3 Community
Twitter https://twitter.com/SOURC3xyz
Discord https://discord.gg/FpE9VfB6

**Comment by JenkJS** [comment]
1. Move it to "beta"
- [X] 2. Add "My organizations" button - done.

**Comment by KatsiarynaV** [comment]
2. Checked

Moved to Beta to fix menu size
